name: reusable workflow A
on:
  workflow_call:
    inputs:
      matrix-input:
        type: string
        required: true

jobs:
  debug-output:
    name: debug output
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(inputs.matrix-input) }}
    steps:
      - run: |
          echo '${{ matrix.key }}'

  call-B:
    uses: ./.github/workflows/B.yml
    strategy:
      matrix: ${{ fromJson(inputs.matrix-input) }}
    with:
      value: ${{ matrix.key }}

