name: Main

on:
  push:
    branches:
      - '**'
    inputs:
      SUPPORTED_ARCH:
        required: true
        type: string


jobs:
  belt_conveyor:
    name: Belt
    uses: ./.github/workflows/belt.yml
    with:
      SUPPORTED_ARCH: '["amd64","arm64"]'
