on:
  workflow_call:
    inputs:
      DOCKER_BUILD_REPO:
        required: true
        type: string
      IMAGE_BASE_NAME:
        required: true
        type: string
      ARCH:
        required: true
        type: string


jobs:
  pre_test:
    name: Pre-test
    runs-on:
      - self-hosted
      - ${{ inputs.ARCH }}
    steps:
      - name: Create matrix
        id: prepare
        run: |
          echo "matrix_tests=[\"['aaa', 'bbb', 'ccc']\",\"['ddd', 'eee', 'fff']\"]" >> $GITHUB_OUTPUT
    outputs:
      matrix_tests: ${{ steps.prepare.outputs.matrix_tests }}
  test:
    name: Test
    needs: pre_test
    if: ${{ always() && needs.pre_test.result == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        batch: ${{ fromJson(needs.pre_test.outputs.matrix_tests) }}
    uses: ./.github/workflows/batch.yml
    with:
      ARCH: ${{ inputs.ARCH }}
      TESTS: ${{ matrix.batch }}